Bump guzzle to 7.4.5
nextcloud/3rdparty pull request #1092
Opened 2022-06-24 14:39 UTC by CarlSchwan

And bump also a bunch of dependencies like was

This needs careful testing

2022-06-24 19:39 UTC, blizzz approved these changes

2022-07-06 11:41 UTC, blizzz requested changes
too many deps affected

2022-07-06 11:47 UTC, blizzz commented
perhaps it's feasible to only patch with the relevant guzzle commit?

2022-07-08 08:26 UTC, szaimen commented
Closing due to https://github.com/nextcloud/3rdparty/pull/1078#issue-1267347802

2022-07-08 08:26 UTC, closed without merging