feat(PSR): ⌚ Add PSR Click interface as dependency
nextcloud/3rdparty pull request #1262
Opened 2022-12-22 17:59 UTC by nickvergessen

Signed-off-by: Joas Schilling <coding@schilljs.com>

2022-12-22 19:02 UTC, ChristophWurst commented
For?

2022-12-22 19:13 UTC, nickvergessen commented
Server PR at https://github.com/nextcloud/server/pull/35872

2022-12-23 14:41 UTC, ChristophWurst approved these changes

2023-01-02 09:02 UTC, come-nc requested changes

2023-01-02 09:02 UTC, come-nc commented on composer/installed.json
> +    "dev": true,
Should not be pushed

2023-01-02 09:02 UTC, come-nc commented on composer/installed.php
>      ),
same

2023-01-02 09:07 UTC, nickvergessen commented on composer/installed.json
> +    "dev": true,
Could be fixed by `composer install --no-dev`

Thanks for the hint

2023-01-02 10:27 UTC, come-nc approved these changes

2023-01-02 10:45 UTC, merged