Bump sabre family
nextcloud/3rdparty pull request #492
Opened 2020-08-21 06:38 UTC by skjnldsv

Fix https://github.com/nextcloud/server/issues/20733

2020-12-14 09:00 UTC, skjnldsv commented
Let's get this in for 21!
Failure is unrelated, it always show a diff of the latest commit :see_no_evil:

2020-12-14 10:26 UTC, ChristophWurst commented on composer/autoload_static.php
> -        'ZipStreamer\\COMPR' => __DIR__ . '/..' . '/deepdiver/zipstreamer/src/ZipStreamer.php',
this is a bit weird

2020-12-14 10:26 UTC, ChristophWurst requested changes
Needs a clean rebase

2020-12-14 10:26 UTC, ChristophWurst commented on sabre/xml/CHANGELOG.md
> +<<<<<<< HEAD
:eye: :lips: :eye:

2020-12-14 10:58 UTC, skjnldsv commented on composer/autoload_static.php
> -        'ZipStreamer\\COMPR' => __DIR__ . '/..' . '/deepdiver/zipstreamer/src/ZipStreamer.php',
I literally did the default vendor setup
If it's happening, I guess it's because master is not up to date?

2020-12-14 11:01 UTC, ChristophWurst commented on composer/autoload_static.php
> -        'ZipStreamer\\COMPR' => __DIR__ . '/..' . '/deepdiver/zipstreamer/src/ZipStreamer.php',
I think to recall that this also happened in another PR.

2020-12-14 12:15 UTC, skjnldsv commented on composer/autoload_static.php
> -        'ZipStreamer\\COMPR' => __DIR__ . '/..' . '/deepdiver/zipstreamer/src/ZipStreamer.php',
It's resolved now, I just did anything the `composer run vendor` would do. This is what CI expects, and I assume, us too :)

2020-12-22 07:20 UTC, ChristophWurst commented on composer/InstalledVersions.php
> -    'interfasys/lognormalizer' =>
this was long killed. how can this still show up in the div?!

2020-12-22 07:21 UTC, ChristophWurst commented on composer/autoload_classmap.php
> -    'ZipStreamer\\COMPR' => $vendorDir . '/deepdiver/zipstreamer/src/ZipStreamer.php',
this doesn't feel right

2020-12-22 07:24 UTC, ChristophWurst commented on composer/autoload_classmap.php
> -    'ZipStreamer\\COMPR' => $vendorDir . '/deepdiver/zipstreamer/src/ZipStreamer.php',
with composer v1

```
Deprecation Notice: Class ZipStreamer\Count64Base located in ./deepdiver/zipstreamer/src/lib/Count64.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ZipStreamer\Count64_32 located in ./deepdiver/zipstreamer/src/lib/Count64.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ZipStreamer\Count64_64 located in ./deepdiver/zipstreamer/src/lib/Count64.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class ZipStreamer\Count64 located in ./deepdiver/zipstreamer/src/lib/Count64.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class Icewind\Streams\UrlCallback located in ./icewind/streams/src/UrlCallBack.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

2020-12-22 07:33 UTC, ChristophWurst commented
I tried my luck with composer v1. That looks a bit less scary: https://github.com/nextcloud/3rdparty/pull/551

2020-12-22 09:58 UTC, closed without merging