Bump pimple/pimple to 3.5.0
nextcloud/3rdparty pull request #905
Opened 2021-11-25 10:10 UTC by come-nc

Signed-off-by: Côme Chilliet <come.chilliet@nextcloud.com>

2021-11-25 16:45 UTC, CarlSchwan commented
Looks good from my side :) Not sure why we didn't need git clean before but it makes sense.

2021-11-25 16:45 UTC, come-nc commented
@ChristophWurst @nickvergessen Can you validate that my CI fix is okay?
The CI has been failing for a week because the tests get inserted in the autoload.

2021-11-26 10:21 UTC, nickvergessen commented
> Can you validate that my CI fix is okay?

But that e.g. would have removed the symfony subdependency in https://github.com/nextcloud/3rdparty/pull/903/files you forgot to add?

2021-11-29 08:14 UTC, come-nc commented
> 



> > Can you validate that my CI fix is okay?
> 
> But that e.g. would have removed the symfony subdependency in https://github.com/nextcloud/3rdparty/pull/903/files you forgot to add?

No, because git clean -X only deletes files ignored by the .gitignore, which is not the case of new dependencies.

2021-11-29 10:35 UTC, ChristophWurst requested changes

2021-11-29 10:35 UTC, ChristophWurst commented on .github/workflows/composer.yml
> +      run: git clean -X -d -f
this would revert https://github.com/nextcloud/3rdparty/pull/815

there was an issue with xdf

2021-11-29 11:14 UTC, come-nc commented on .github/workflows/composer.yml
> +      run: git clean -X -d -f
Wait, so the tests are supposed to be in the autoload then?

2021-11-29 11:24 UTC, ChristophWurst commented on .github/workflows/composer.yml
> +      run: git clean -X -d -f
IMO no, they shouldn't. But I lack the context on the other PR. Just linked it to show xdf was used before and it was intentionally removed :)

2021-11-29 13:14 UTC, come-nc commented
Commit https://github.com/nextcloud/3rdparty/commit/2ae1a1d6f688ae8394d6559ee673fecbee975db4 has removed tests from the autoload and all commits since have been failing CI.

2021-11-29 13:43 UTC, come-nc commented on .github/workflows/composer.yml
> +      run: git clean -X -d -f
Actually before #815 it was `git clean -x` which would remove any new file. My commit uses `git clean -X` which only removes files covered by .gitignore
So it should be fine IMO.

2021-11-29 13:51 UTC, ChristophWurst approved these changes

2021-11-29 13:53 UTC, merged